name: Build/release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
      
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}